CI: fix #NOCI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -461,7 +461,13 @@ jobs:
           cp -v target/release/hitdns bin/$(git log -1 --format="%cd" --date=format:"%Y-%m-%d_%H-%M-%S" ${{github.sha}})__${{github.sha}}/hitdns.amd64-mac
           git add -A
           git commit -m "[${{github.sha}}] upload binary of hitdns amd64 mac"
-          git push origin bin
+
+          for i in {1..5}
+          do
+              echo try push $i
+              git push origin bin && break || true # why this rejected by github?   ! [rejected] bin -> bin (fetch first) error: failed to push some refs to 'https://github.com/delta4chat/hitdns'
+          done
+
           git switch this
           git reset --hard ${{github.sha}}
 
